name: CI

on:
  push:
    branches: [main]

env:
  DOTNET_NOLOGO: true

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15

      - uses: xt0rted/markdownlint-problem-matcher@v1.1.0

      - run: yarn install

      - run: yarn test

  build:
    needs: lint-markdown

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup .NET Core (3.1.x)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET Core (global.json)
        uses: actions/setup-dotnet@v1.7.2

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --output ./artifacts --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          path: ./artifacts/*

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --no-symbols true \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
