name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.0

      - name: Install Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 15

      - uses: xt0rted/markdownlint-problem-matcher@v1.1.0

      - run: yarn install

      - run: yarn test

  build:
    needs: lint-markdown

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.0

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x

      - name: Set up .NET Core (global.json)
        uses: actions/setup-dotnet@v2.0.0

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --no-build --output ./artifacts --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./artifacts/*.nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
