# https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
name: Dependabot auto-merge

on: pull_request_target

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.DEPENDAMERGE_APP_ID }}
          private_key: ${{ secrets.DEPENDAMERGE_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependabot ecosystem
        uses: actions/github-script@v5.1.0
        id: metadata
        with:
          script: |
            // https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem
            const ecosystems = {
              bundler: "bundler",
              cargo: "cargo",
              composer: "composer",
              docker: "docker",
              elm: "elm",
              github_actions: "github-actions",
              go_modules: "gomod",
              gradle: "gradle",
              hex: "mix",
              maven: "maven",
              npm_and_yarn: "npm",
              nuget: "nuget",
              pip: "pip",
              submodules: "gitsubmodule",
              terraform: "terraform",
            };

            const branchName = context.payload.pull_request.head.ref;
            const [, branchEnvironment] = branchName.split("/");
            const ecosystem = ecosystems[branchEnvironment];

            if (!ecosystem) {
              core.setFailed(`No ecosystem found in branch: ${branchName}`);
              return;
            }

            core.info(`dependency-ecosystem detected: ${ecosystem}`);
            core.setOutput("dependency-ecosystem", ecosystem);

      - name: Authenticate cli
        run: echo "${{ steps.generate_token.outputs.token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.dependency-ecosystem == 'github-actions' || (steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch') }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          
