name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.4.0

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --no-build --output ./artifacts --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./artifacts/*.nupkg

  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Install Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 15

      - uses: xt0rted/markdownlint-problem-matcher@v1.1.0

      - run: yarn install

      - run: yarn test
