name: Pull Request

on: pull_request

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1.9.1
        with:
          dotnet-version: |
            3.1.x
            5.0.x

      - name: Set up .NET Core (global.json)
        uses: actions/setup-dotnet@v1.9.1

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --no-build --output ./artifacts --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          path: ./artifacts/*.nupkg

  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0

      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 15

      - uses: xt0rted/markdownlint-problem-matcher@v1.1.0

      - run: yarn install

      - run: yarn test

  message-check:
    name: Block on fixup commits

    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/block-autosquash-commits-action@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
