name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x

      - name: Set up .NET Core (global.json)
        uses: actions/setup-dotnet@v2.0.0

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Publish artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./artifacts/*.nupkg

      - name: Upload release assets
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/*.nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}

      - name: Publish to nuget.org
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json
